### PR TITLE
Added read_color_layouts for reading PCR layouts with targets encoded by color

### PR DESCRIPTION
**Pull request by taylo5jm**
`read_color_layouts` is the powerhouse. This is not ready to be merged yet, because I am going to write some tests. Just wanted to share now so you can use it and provide feedback.

### CODE REVIEW

**Comment by nathancday** [comment]
this looks cool! gonna take it out for a spin right now!

**Comment by taylo5jm** [comment]
I pushed a fix that should solve the problem with the BDG0203-6 case. The NTC wells with no target were causing the issue. Now, the function will return the result and those wells are just given `NA` for `target`.

**Comment by taylo5jm** [comment]
@nathancday I've added tests for the `find_plates` function. The function is in `pcr_utils.R`, but maybe should be moved elsewhere, since it has more applications than PCR. 

What are your thoughts on the `read_color_layouts` function? I think requiring `xlsx` is a bad idea, just because it such a pain to manage its dependencies. On the other hand, I have been using it for PCR and will probably continue to do so.

**Comment by nathancday** [comment]
I don't think there is any harm in adding `read_color_layouts()`, in fact I think we should. Like you said it's very useful, let's just make the documentation explicit about the xlsx requirement.

I think we can add `xlsx` to "Suggests" instead of "Imports" and that should be enough to allow package install without forcing everyone to fight `rJava`.

**Comment by taylo5jm** [comment]
@nathancday I added `xlsx` to `DESCRIPTION` and also added a warning about the xlsx requirement in the roxygen2 documentation. 

What is the policy for writing tests for functions that call objects from suggested packages?

**Pull request closed without merging**
