### PR TITLE
new function to build c3-c2 ratios in PH scripts

### PR DESCRIPTION
**Pull request by nathancday**

### CODE REVIEW

**Comment by nathancday** [comment]
I'd like feedback on improvements for durability and syntax.

**Comment by taylo5jm** [comment]
Small potatoes, but we might want to `@importFrom magrittr %<>%`. The forward pipe is loaded by `dplyr`, but not the reciprocal pipe. 

In addition to 13C/12C issue, we might need to add functionality for computing the ratio for the nuclear-normalized concentrations (`conc_incell_uM`).

**Comment by nathancday** [comment]
My plan was for this function to be upstream of nuc_join(). Which would
save us from the intracellular concentration handling. Does that seem like
a long term sustainable?

**Comment by taylo5jm** [comment]
I think that makes sense and it would keep this function as concise as possible.

For the 12C vs. 13C problem, how about we add an argument, perhaps `prop_targ` (`propionyl_target`), which can be either `12C-Propionyl-Car` or `13C-Propionyl-Car`? The name of the acetyl-carnitine will always be `12C-Acetyl-Car`, so no need to expose that in the signature.

**Comment by nathancday** [comment]
I like that. Let's finish it tomorrow.

**Comment by nathancday** [comment]
@taylo5jm please review the updated signature of `make_c3c2()`

**Pull request merged**
